# vetinari — top-level developer recipes
#
# Run inside `nix-shell` (or with direnv) so rustc, cargo, jj, claude-sandbox
# and zellij are all on PATH at their pinned versions.

set shell := ["bash", "-euo", "pipefail", "-c"]
set dotenv-load := false

# Resolve the workspace root once so recipes work from any subdir.
project_root := justfile_directory()

# Default recipe prints the menu.
default:
    @just --list

# Format check (rustfmt) + clippy (deny warnings) + cargo build, plus the
# repo-local xtask lint once #6 (F6) lands. The lint invocation is left as a
# `just lint` call so it can grow without touching this recipe.
build:
    cargo build --workspace --all-targets

# Release build of the main orchestrator binary.
build-release:
    cargo build --release -p orchestrator

# Wire the nix-provided source trees into the cargo build (REQ-1):
#   - .cargo/config.toml redirects the `jj-lib` crates.io dependency to the
#     jujutsu source the dev shell pins ($JJ_SRC), so the orchestrator links
#     the *exact* jj version the workers drive via the `jj` CLI (REQ-1c).
#   - .crosslink-src is a *writable copy* of the npins-pinned crosslink source
#     ($CROSSLINK_SRC) so `crosslink_api` can path-depend on the `crosslink`
#     library crate (REQ-3a). crosslink is not on crates.io, so a `[patch]`
#     cannot be used; and crosslink's build.rs writes a dashboard placeholder
#     into the tree, so a symlink into the read-only nix store will not do.
# Both are .gitignore'd and per-host (the store paths change on a pin bump).
# The dev-shell shellHook runs this on entry, so a bare `cargo build` also works.
bootstrap:
    #!/usr/bin/env bash
    set -euo pipefail
    : "${JJ_SRC:?JJ_SRC not set — run inside the nix dev shell (nix-shell / direnv)}"
    : "${CROSSLINK_SRC:?CROSSLINK_SRC not set — run inside the nix dev shell (nix-shell / direnv)}"
    mkdir -p "{{ project_root }}/.cargo"
    {
      printf '# Generated by `just bootstrap` — DO NOT EDIT, DO NOT COMMIT.\n'
      printf '# Redirects jj-lib to the jujutsu source the nix dev shell pins,\n'
      printf '# so the orchestrator and the workers share one jj version.\n'
      printf '# Regenerated on every dev-shell entry. (REQ-1, REQ-1c)\n'
      printf '[patch.crates-io]\n'
      printf 'jj-lib = { path = "%s/lib" }\n' "$JJ_SRC"
    } > "{{ project_root }}/.cargo/config.toml"
    echo "bootstrap: wrote .cargo/config.toml (jj-lib -> $JJ_SRC/lib)"
    # crosslink: copy the source to a writable tree, but only when the pinned
    # store path has changed — re-copying every entry would needlessly churn
    # mtimes and trigger crosslink rebuilds.
    crosslink_dest="{{ project_root }}/.crosslink-src"
    crosslink_marker="$crosslink_dest/.vetinari-pinned-src"
    if [ "$(cat "$crosslink_marker" 2>/dev/null || true)" != "$CROSSLINK_SRC" ]; then
      rm -rf "$crosslink_dest"
      cp -r --no-preserve=mode,ownership "$CROSSLINK_SRC" "$crosslink_dest"
      printf '%s' "$CROSSLINK_SRC" > "$crosslink_marker"
      echo "bootstrap: copied crosslink source -> .crosslink-src ($CROSSLINK_SRC)"
    else
      echo "bootstrap: .crosslink-src already current ($CROSSLINK_SRC)"
    fi
    # crosslink's server module embeds dashboard/dist via rust-embed; ensure
    # the folder exists so the derive compiles without a built frontend.
    mkdir -p "$crosslink_dest/dashboard/dist"
    if [ ! -f "$crosslink_dest/dashboard/dist/index.html" ]; then
      printf '<!doctype html><title>crosslink dashboard placeholder</title>\n' \
        > "$crosslink_dest/dashboard/dist/index.html"
    fi

# Run unit + integration tests. nextest if available, falls back to cargo test.
test:
    @if command -v cargo-nextest >/dev/null 2>&1; then \
        cargo nextest run --workspace; \
    else \
        cargo test --workspace; \
    fi

# Format check + clippy (deny warnings) + xtask no-shell-out lint (AC-24).
#
# `xtask lint` exits 0 (clean) or 1 (forbidden shell-out found). Exit 2 is
# reserved for xtask subcommands that are recognized but not yet implemented
# and is treated as a clean skip; any other non-zero code fails the recipe.
lint:
    cargo fmt --all -- --check
    cargo clippy --workspace --all-targets -- -D warnings
    @set +e; \
    cargo run --quiet --bin xtask -- lint 2>&1; \
    code=$?; \
    if [ "$code" -eq 0 ] || [ "$code" -eq 2 ]; then exit 0; else exit "$code"; fi

# Apply formatting.
fmt:
    cargo fmt --all

# Run the orchestrator against this repo. On startup it ensures the long-lived
# headless zellij session `vdd-orchestrator` exists (REQ-1d, #7) — created on
# first run, reused afterwards. Inspect a running worker live by attaching to
# it from another terminal:
#
#     zellij attach vdd-orchestrator
#
# The full pump-driven behavior lands across #8..#19.
orchestrate:
    cargo run --release -p orchestrator

# Dogfood loop. Will be wired to the fixture-based test in #19 (G1).
dogfood:
    @echo "dogfood loop ships with #19 (G1) — see .design/vdd-orchestrator.md AC-11a/11b"
    @exit 0

# Clean every build artifact. Keeps the dev shell otherwise untouched.
clean:
    cargo clean

# Show what's blocking what — handy when picking the next issue to work on.
graph:
    @if command -v crosslink >/dev/null 2>&1; then \
        crosslink issue blocked; \
        echo; \
        echo "Ready to work on:"; \
        crosslink issue ready; \
    else \
        echo "crosslink not on PATH — re-enter the dev shell"; \
        exit 1; \
    fi
