# vetinari — top-level developer recipes
#
# Run inside `nix-shell` (or with direnv) so rustc, cargo, jj, claude-sandbox
# and zellij are all on PATH at their pinned versions.

set shell := ["bash", "-euo", "pipefail", "-c"]
set dotenv-load := false

# Resolve the workspace root once so recipes work from any subdir.
project_root := justfile_directory()

# Default recipe prints the menu.
default:
    @just --list

# Format check (rustfmt) + clippy (deny warnings) + cargo build, plus the
# repo-local xtask lint once #6 (F6) lands. The lint invocation is left as a
# `just lint` call so it can grow without touching this recipe.
build:
    cargo build --workspace --all-targets

# Release build of the main orchestrator binary.
build-release:
    cargo build --release -p orchestrator

# Generate .cargo/config.toml, redirecting the `jj-lib` crates.io dependency
# to the jujutsu source tree the nix dev shell pins ($JJ_SRC). This is how the
# orchestrator links the *exact* jj version the workers drive via the `jj` CLI
# (REQ-1, REQ-1c). The file is regenerated wholesale because the nix store
# path changes whenever the pinned jujutsu is bumped; it is .gitignore'd. The
# dev-shell shellHook runs this on entry, so a bare `cargo build` also works.
bootstrap:
    #!/usr/bin/env bash
    set -euo pipefail
    : "${JJ_SRC:?JJ_SRC not set — run inside the nix dev shell (nix-shell / direnv)}"
    mkdir -p "{{ project_root }}/.cargo"
    {
      printf '# Generated by `just bootstrap` — DO NOT EDIT, DO NOT COMMIT.\n'
      printf '# Redirects jj-lib to the jujutsu source the nix dev shell pins,\n'
      printf '# so the orchestrator and the workers share one jj version.\n'
      printf '# Regenerated on every dev-shell entry. (REQ-1, REQ-1c)\n'
      printf '[patch.crates-io]\n'
      printf 'jj-lib = { path = "%s/lib" }\n' "$JJ_SRC"
    } > "{{ project_root }}/.cargo/config.toml"
    echo "bootstrap: wrote .cargo/config.toml (jj-lib -> $JJ_SRC/lib)"

# Run unit + integration tests. nextest if available, falls back to cargo test.
test:
    @if command -v cargo-nextest >/dev/null 2>&1; then \
        cargo nextest run --workspace; \
    else \
        cargo test --workspace; \
    fi

# Format check + clippy (deny warnings) + xtask no-shell-out lint (AC-24).
#
# `xtask lint` exits 0 (clean) or 1 (forbidden shell-out found). Exit 2 is
# reserved for xtask subcommands that are recognized but not yet implemented
# and is treated as a clean skip; any other non-zero code fails the recipe.
lint:
    cargo fmt --all -- --check
    cargo clippy --workspace --all-targets -- -D warnings
    @set +e; \
    cargo run --quiet --bin xtask -- lint 2>&1; \
    code=$?; \
    if [ "$code" -eq 0 ] || [ "$code" -eq 2 ]; then exit 0; else exit "$code"; fi

# Apply formatting.
fmt:
    cargo fmt --all

# Run the orchestrator against this repo. The full pump-driven behavior lands
# across #7..#19. For now this just runs the skeleton main() so we can confirm
# the toolchain end-to-end.
orchestrate:
    cargo run --release -p orchestrator

# Dogfood loop. Will be wired to the fixture-based test in #19 (G1).
dogfood:
    @echo "dogfood loop ships with #19 (G1) — see .design/vdd-orchestrator.md AC-11a/11b"
    @exit 0

# Clean every build artifact. Keeps the dev shell otherwise untouched.
clean:
    cargo clean

# Show what's blocking what — handy when picking the next issue to work on.
graph:
    @if command -v crosslink >/dev/null 2>&1; then \
        crosslink issue blocked; \
        echo; \
        echo "Ready to work on:"; \
        crosslink issue ready; \
    else \
        echo "crosslink not on PATH — re-enter the dev shell"; \
        exit 1; \
    fi
