# vetinari — top-level developer recipes
#
# Run inside `nix-shell` (or with direnv) so rustc, cargo, jj, claude-sandbox
# and zellij are all on PATH at their pinned versions.

set shell := ["bash", "-euo", "pipefail", "-c"]
set dotenv-load := false

# Resolve the workspace root once so recipes work from any subdir.
project_root := justfile_directory()

# Default recipe prints the menu.
default:
    @just --list

# Format check (rustfmt) + clippy (deny warnings) + cargo build, plus the
# repo-local xtask lint once #6 (F6) lands. The lint invocation is left as a
# `just lint` call so it can grow without touching this recipe.
build:
    cargo build --workspace --all-targets

# Release build of the main orchestrator binary.
build-release:
    cargo build --release -p orchestrator

# Bootstrap step. F1 ships an empty .cargo/config.toml because crosslink_api
# (#3) and jj_api (#4) don't yet need path injection — once those land, this
# recipe will template the file from environment variables provided by the
# nix dev shell. Until then it just ensures the file exists for tooling that
# expects to find it.
bootstrap:
    mkdir -p {{ project_root }}/.cargo
    @if [ ! -f {{ project_root }}/.cargo/config.toml ]; then \
        printf '# Generated by `just bootstrap`. Path injection lands in #3 (F3) and #4 (F4).\n' > {{ project_root }}/.cargo/config.toml; \
        echo "wrote .cargo/config.toml (empty)"; \
    else \
        echo ".cargo/config.toml already exists — leaving untouched"; \
    fi

# Run unit + integration tests. nextest if available, falls back to cargo test.
test:
    @if command -v cargo-nextest >/dev/null 2>&1; then \
        cargo nextest run --workspace; \
    else \
        cargo test --workspace; \
    fi

# Format check + clippy (deny warnings) + xtask no-shell-out lint (AC-24).
#
# `xtask lint` exits 0 (clean) or 1 (forbidden shell-out found). Exit 2 is
# reserved for xtask subcommands that are recognized but not yet implemented
# and is treated as a clean skip; any other non-zero code fails the recipe.
lint:
    cargo fmt --all -- --check
    cargo clippy --workspace --all-targets -- -D warnings
    @set +e; \
    cargo run --quiet --bin xtask -- lint 2>&1; \
    code=$?; \
    if [ "$code" -eq 0 ] || [ "$code" -eq 2 ]; then exit 0; else exit "$code"; fi

# Apply formatting.
fmt:
    cargo fmt --all

# Run the orchestrator against this repo. The full pump-driven behavior lands
# across #7..#19. For now this just runs the skeleton main() so we can confirm
# the toolchain end-to-end.
orchestrate:
    cargo run --release -p orchestrator

# Dogfood loop. Will be wired to the fixture-based test in #19 (G1).
dogfood:
    @echo "dogfood loop ships with #19 (G1) — see .design/vdd-orchestrator.md AC-11a/11b"
    @exit 0

# Clean every build artifact. Keeps the dev shell otherwise untouched.
clean:
    cargo clean

# Show what's blocking what — handy when picking the next issue to work on.
graph:
    @if command -v crosslink >/dev/null 2>&1; then \
        crosslink issue blocked; \
        echo; \
        echo "Ready to work on:"; \
        crosslink issue ready; \
    else \
        echo "crosslink not on PATH — re-enter the dev shell"; \
        exit 1; \
    fi
